## Generated by configure

ifneq ($(PLATFORM_CONFIG_INCLUDED), yes)
PLATFORM_CONFIG_INCLUDED=yes

PLATFORM_DIR=/home/xiang/projects/rk3188/embuild/platform

REMOTE_HOST=192.168.10.10
BOARD=rk3188
SVR_DEF_USER=pub
RK3188_BOOT_MODE=nand-emmc
ROOTFS_TYPE=squashfs
include /home/xiang/projects/rk3188/embuild/platform/defconfig.mk

endif
